In [57]:
import numpy as np

def getCoefPolInter(x, y):
    
    A = np.zeros(shape=(len(x), len(x)))
    
    for i in range(len(x)):
        for j in range(len(x)):
            A[i][j] = x[i] ** j
    
    return np.linalg.solve(A, y)

x = np.linspace(-1,1,20)
y = np.sin(x)

print(getCoefPolInter(x, y))

[  0.00000000e+00   1.00000000e+00  -1.24649215e-15  -1.66666667e-01
   6.04826660e-14   8.33333333e-03  -9.41480904e-13  -1.98412692e-04
   7.24135160e-12   2.75569249e-06  -3.05549966e-11  -2.49038191e-08
   7.33402243e-11  -1.65049726e-10  -9.91588754e-11   4.10849305e-10
   6.99461639e-11  -2.76025366e-10  -1.99316226e-11   7.57208593e-11]


In [58]:
import numpy as np

x = [1,1,1,1,1,1,1,1,1,1]

A = np.zeros(shape=(len(x), len(x)))

print(A)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
